services:
  django:
    image: black_skoleni
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - 8000:8000
    volumes:
      - .:/app